apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: gotify
spec:
  name: gotify
  deploymentstrategy: docker
  image:
    repository: gotify/server
    tag: latest
    containerPort: "8080"
  addons: []
  envVars:
  - name: GOTIFY_DEFAULTUSER_NAME
    value: admin
  - name: GOTIFY_DEFAULTUSER_PASS
    value: admin
  - name: GOTIFY_SERVER_PORT
    value: "8080"
  - name: GOTIFY_REGISTRATION
    value: "false"
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /app/data
    name: gotify-volume
    size: 1Gi
    storageClass:
  web:
    replicaCount: 1
  worker:
    replicaCount: 0