apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: n8n
spec:
  name: n8n
  deploymentstrategy: docker
  image:
    repository: docker.n8n.io/n8nio/n8n
    tag: latest
    containerPort: "5678"
  addons: 
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: n8n-postgres
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: postgres
                  password: "123456"
                  postgresPassword: postgres
                  username: n8n
              storageClass: linode-block-storage
            primary:
              persistence:
                size: 1Gi
  envVars: 
  - name: DB_TYPE
    value: postgresdb
  - name: DB_POSTGRESDB_HOST
    value: n8n-postgres-postgresql
  - name: DB_POSTGRESDB_PORT
    value: "5432"
  - name: DB_POSTGRESDB_USER
    value: n8n
  - name: DB_POSTGRESDB_PASSWORD
    value: "123456"
  - name: N8N_BASIC_AUTH_ACTIVE
    value: "false"
  - name: DB_POSTGRESDB_DATABASE
    value: postgres
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0