name: Maputnik
description: 'A free and open visual editor for the Mapbox GL styles targeted at developers and map designers.'
tags:
- mapping
- maps
- cartography
source: https://github.com/maputnik/editor
website: https://maputnik.github.io/editor/
icon: https://avatars.githubusercontent.com/u/22297422?s=200&v=4
screenshots:
- https://camo.githubusercontent.com/e417a4c766f2f3245803f93ed2bdad17d13f20d114330e2436f91ecfadd1e7bf/68747470733a2f2f6a2e676966732e636f6d2f6b3567384f4a2e676966