kubero:
  clusterissuer: letsencrypt-prod
  readonly: false
  banner:
    show: false
    message: "Welcome to Kubero!"
    bgcolor: "#8560A9"
    fontcolor: "azure"
  defaultannotations:
    apps:
    pipelines:
      - janitor/ttl=5m
templates:
  enabled: true
  catalogs:
  - name: "Kubero"
    description: "Kubero templates"
    templateBasePath: "https://raw.githubusercontent.com/kubero-dev/kubero/main/services/"
    index: 
      url: "https://raw.githubusercontent.com/kubero-dev/templates/main/index.json"
      format: "json" # json or yaml # TODO has no effect yet. json is always used
  - name: "Kubero Frameworks"
    description: "Kubero templates"
    templateBasePath: "https://raw.githubusercontent.com/kubero-dev/kubero/main/services/"
    index: 
      url: "https://raw.githubusercontent.com/kubero-dev/templates/main/index-frameworks.json"
      format: "json" # json or yaml # TODO has no effect yet. json is always used
buildpacks:
  - name: NodeJS
    language: JavaScript
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    build:
      repository: node
      tag: latest
      command: "npm install"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: node
      tag: latest
      command: "node index.js"
      readOnlyAppStorage: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
  - name: PHP
    language: PHP
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    build:
      repository: composer
      tag: latest
      command: "composer install; chown -R 1000:1000 /app"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: ghcr.io/kubero-dev/buildpacks/php
      tag: "main"
      command: "apache2-foreground"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        allowPrivilegeEscalation: true
        readOnlyRootFilesystem: false
        capabilities:
          add: []
          drop: []
  - name: Python
    language: Python
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    build:
      repository: python
      tag: 3.10-buster
      command: "python3 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: python
      tag: 3.10-buster
      command: ". .venv/bin/activate && python3 main.py"
      readOnlyAppStorage: true
      securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop: []
  - name: GoLang
    language: GoLang
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
          runAsUser: 0
          runAsGroup: 0
          runAsNonRoot: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            add: []
            drop: []
    build:
      repository: golang
      tag: alpine
      command: "go mod download && go mod verify && go build -v -o app"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: golang
      tag: alpine
      command: "./app"
      readOnlyAppStorage: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
  - name: Hugo
    language: GoLang
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    build:
      repository: klakegg/hugo
      tag: latest
      command: hugo -D
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: caddy
      tag: latest
      command: caddy file-server --listen :8080 --root /app/public
      readOnlyAppStorage: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
  - name: Ruby
    language: Ruby
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    build:
      repository: ruby
      tag: "2.7"
      command: "export GEM_HOME=/app/bundle; bundle install --jobs=4 --retry=3"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: ruby
      tag: "2.7"
      command: "export GEM_HOME=/app/bundle; bundle exec ruby main.rb"
      readOnlyAppStorage: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
  - name: Static
    language: HTML
    fetch:
      repository: ghcr.io/kubero-dev/buildpacks/fetch
      tag: v1.2
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    build:
      repository: busybox
      tag: latest
      command: "echo 'Buildpack not required'"
      readOnlyAppStorage: false
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
    run:
      repository: caddy
      tag: latest
      command: caddy file-server --listen :8080 --root /app
      readOnlyAppStorage: true
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
podSizeList:
- name: small
  description: 'Small (CPU: 0.25, Memory: 0.5Gi)'
  default: true
  resources:
    requests:
      memory: 0.5Gi
      cpu: 250m
    limits:
      memory: 1Gi
      cpu: 500m
- name: medium
  description: 'Medium (CPU: 1, Memory: 2Gi)'
  resources:
    requests:
      memory: 2Gi
      cpu: 1000m
    limits:
      memory: 4Gi
      cpu: 2000m
- name: large
  description: 'Large (CPU: 2, Memory: 4Gi)'
  active: false
  resources:
    requests:
      memory: 4Gi
      cpu: 2000m
