apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: etherpad
spec:
  name: etherpad
  deploymentstrategy: docker
  image:
    repository: etherpad/etherpad
    tag: latest
    containerPort: "8080"
    run:
      securityContext:
        readOnlyRootFilesystem: false
  addons: 
  - displayName: Kubero Postgresql
    env: []
    icon: /img/addons/postgresql.png
    id: kubero-operator
    kind: KuberoPostgresql
    resourceDefinitions:
      KuberoPostgresql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoPostgresql
        metadata:
          name: etherpad-postgresql
        spec:
          postgresql:
            global:
              postgresql:
                auth:
                  database: postgresql
                  password: etherpad
                  postgresPassword: etherpad
                  username: etherpad
              storageClass: standard
            primary:
              persistence:
                size: 1Gi
  envVars: 
  - name: DB_TYPE
    value: postgres
  - name: DB_PASS
    value: etherpad
  - name: DB_USER
    value: etherpad
  - name: DB_NAME
    value: postgresql
  - name: DB_HOST
    value: etherpad-postgresql
  - name: DB_PORT
    value: "5432"
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0