name: Etherpad
description: 'Etherpad is a real-time collaborative editor scalable to thousands of simultaneous real time users.'
tags:
- collaboration
- documents
- editor
- writing
source: https://github.com/ether/etherpad-lite
website: https://etherpad.org/
documentation:
- https://github.com/ether/etherpad-lite/blob/develop/doc/docker.md
icon: https://avatars.githubusercontent.com/u/181731?s=200&v=4
screenshots:
- https://raw.githubusercontent.com/ether/etherpad-lite/develop/doc/images/etherpad_demo.gif