apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: hopscotch
spec:
  name: hopscotch
  deploymentstrategy: docker
  image:
    repository: hoppscotch/hoppscotch
    tag: latest
    containerPort: "3000"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0