apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: passbolt
spec:
  name: passbolt
  deploymentstrategy: docker
  image:
    repository: passbolt/passbolt
    tag: latest-ce
    containerPort: "80"
  addons: 
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: passbolt-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: passbolt
              password: changeme
              rootPassword: changeme
              username: passbolt
            global:
              storageClass: standard
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
  envVars: 
  - name: APP_FULL_BASE_URL
    value: http://passbolt.mydomain.com
  - name: DATASOURCES_DEFAULT_HOST
    value: passbolt-mysql
  - name: DATASOURCES_DEFAULT_USERNAME
    value: passbolt
  - name: DATASOURCES_DEFAULT_PASSWORD
    value: changeme
  - name: DATASOURCES_DEFAULT_DATABASE
    value: passbolt
  cronjobs: []
  extraVolumes: 
  - mountPath: /etc/passbolt/gpg
    name: passbolt-gpg-volume
    size: 1Gi
  - mountPath: /etc/passbolt/jwt
    name: passbolt-jwt-volume
    size: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0