apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: nocodb
spec:
  name: nocodb
  deploymentstrategy: docker
  image:
    repository: nocodb/nocodb
    tag: latest
    containerPort: "8080"
    run:
      securityContext:
        readOnlyRootFilesystem: false
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /usr/app/data/
    name: nocodb-data-volume
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0