apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: excalidraw
spec:
  name: excalidraw
  deploymentstrategy: docker
  image:
    repository: excalidraw/excalidraw
    tag: latest
    containerPort: "80"
    run:
      securityContext:
        readOnlyRootFilesystem: false
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0