name: Excalidraw
description: 'An open source virtual hand-drawn style whiteboard. Collaborative and end-to-end encrypted.'
tags:
- drawing
- collaboration
- whiteboard
source: https://github.com/excalidraw/excalidraw
website: https://excalidraw.com/
icon: https://avatars.githubusercontent.com/u/59452120?s=200&v=4
screenshots:
- https://excalidraw.nyc3.cdn.digitaloceanspaces.com/github%2Fproduct_showcase.png