name: Appsmith
description: 'Low code project to build admin panels, internal tools, and dashboards. Integrates with 15+ databases and any API.'
tags:
- admin-dashboard
- workflows
- app-builder
source: https://github.com/appsmithorg/appsmith
website: https://www.appsmith.com
icon: https://avatars.githubusercontent.com/u/67620218?s=200&v=4
screenshots:
- https://images.ctfassets.net/lpvian6u6i39/57xRxbPxLB5Rx6YYCQstyW/d605683e09640cabbb15e9a9d65dc03d/img-cta.png