apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: gitea
spec:
  name: gitea
  deploymentstrategy: docker
  image:
    repository: gitea/gitea
    tag: latest
    containerPort: "3000"
    run:
      securityContext:
        readOnlyRootFilesystem: false
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /data
    name: gitea-data
    size: 10Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0