apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: kuma
spec:
  name: kuma
  deploymentstrategy: docker
  image:
    repository: louislam/uptime-kuma
    tag: latest
    containerPort: "8080"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /app/data
    name: kuma-data
    size: 1Gi
    storageClass:
  web:
    replicaCount: 1
  worker:
    replicaCount: 0