apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: serge
spec:
  name: serge
  deploymentstrategy: docker
  image:
    repository: ghcr.io/serge-chat/serge
    tag: latest
    containerPort: "8008"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /usr/src/app/weights
    name: weights
    size: 70Gi
    storageClass: standard
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /data/db
    name: datadb
    size: 1Gi
    storageClass: standard
  web:
    replicaCount: 1
  worker:
    replicaCount: 0