apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: databag
    labels:
        manager: kubero
spec:
    name: databag
    deploymentstrategy: docker
    envVars:
        - name: ADMIN
          value: secret
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /var/lib/databag
          name: databag-data
          size: 1Gi
          storageClass:
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "7000"
        pullPolicy: Always
        repository: balzack/databag
        tag: latest
