apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: tasksmd
spec:
  name: tasksmd
  deploymentstrategy: docker
  image:
    repository: baldissaramatheus/tasks.md
    tag: latest
    containerPort: "8080"
  addons: []
  envVars: 
  - name: TITLE
    value: Demo
  cronjobs: []
  extraVolumes: 
  - accessModes:
    - ReadWriteMany
    mountPath: /api/files/
    name: tasksmd-files
    size: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0