name: Docker Registry
description: 'The Registry is a stateless, highly scalable server side application that stores and lets you distribute Docker images.'
tags:
- docker
source: https://github.com/distribution/distribution
website: https://docs.docker.com/registry/
icon: https://avatars.githubusercontent.com/u/5429470?s=200&v=4
screenshots: