apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: ryot
    labels:
        manager: kubero
spec:
    name: ryot
    deploymentstrategy: docker
    envVars:
        - name: DATABASE_URL
          value: postgres://ryot:ryot@ryot-postgresql:5432/ryot
        - name: DISABLE_TELEMETRY
          value: "false"
    extraVolumes: []
    cronjobs: []
    addons:
        - displayName: Postgresql
          env: []
          icon: /img/addons/postgresql.png
          id: kubero-operator
          kind: KuberoPostgresql
          resourceDefinitions:
              KuberoPostgresql:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoPostgresql
                  metadata:
                      name: ryot-postgresql
                  spec:
                      postgresql:
                          global:
                              postgresql:
                                  auth:
                                      database: ryot
                                      password: ryot
                                      postgresPassword: postgres
                                      username: ryot
                              storageClass:
                          primary:
                              persistence:
                                  size: 1Gi
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "8000"
        pullPolicy: Always
        repository: ghcr.io/ignisda/ryot
        tag: latest
