name: Coral
description: 'A better onlne commenting experience from Vox Media'
tags:
- commments
- community
source: https://github.com/coralproject/talk
website: https://coralproject.net
documentation: 
- https://docs.coralproject.net/
- https://github.com/coralproject/talk/blob/main/docs/docs/environment-variables.md
icon: https://avatars.githubusercontent.com/u/9255912?s=200&v=4
screenshots:
