name: Shiori
description: 'Shiori is a simple bookmark manager. '
tags:
- bookmark manager
source: https://github.com/go-shiori/shiori
website: https://github.com/go-shiori/shiori
icon: https://raw.githubusercontent.com/go-shiori/shiori/master/internal/view/assets/res/apple-touch-icon-152x152.png
screenshots:
- https://raw.githubusercontent.com/go-shiori/shiori/master/docs/readme/cover.png
- https://raw.githubusercontent.com/go-shiori/shiori/master/docs/screenshots/02-home.png
- https://raw.githubusercontent.com/go-shiori/shiori/master/docs/screenshots/04-options.png