name: Unleash
description: 'Unleash is an open source feature management solution.'
tags:
- feature-toggle
source: https://github.com/Unleash/unleash
website: https://getunleash.io/
icon: https://avatars.githubusercontent.com/u/23053233?s=200&v=4
screenshots:
- https://raw.githubusercontent.com/Unleash/unleash/main/.github/github_online_demo.svg