apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: ntfy
spec:
  name: ntfy
  deploymentstrategy: docker
  image:
    repository: binwiederhier/ntfy
    tag: latest
    containerPort: "80"
    command:
      - ntfy
      - serve
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
    - accessModes:
        - ReadWriteOnce
      emptyDir: false
      mountPath: /var/cache/ntfy
      name: ntfy-cache-volume
      size: 500Mi
      storageClass:
  web:
    replicaCount: 1
  worker:
    replicaCount: 0