name: NTFY
description: 'ntfy (pronounced "notify") is a simple HTTP-based pub-sub notification service. With ntfy, you can send notifications to your phone or desktop via scripts from any computer, without having to sign up or pay any fees'
tags:
- notifications
- push
- pubsub
source: https://github.com/binwiederhier/ntfy
website: https://ntfy.sh/
icon: https://ntfy.sh/_next/static/media/logo.077f6a13.svg
screenshots:
- https://ntfy.sh/static/img/screenshot-web-detail.png
- https://ntfy.sh/static/img/screenshot-curl.png
- https://ntfy.sh/static/img/screenshot-phone-notification.jpg
- https://ntfy.sh/static/img/screenshot-phone-detail.jpg
