apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: ghost
spec:
  name: ghost
  deploymentstrategy: docker
  image:
    repository: ghost
    tag: latest
    containerPort: "2368"
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: ghost-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: ghost
              password: ghost
              rootPassword: ghost
              username: ghost
            global:
              storageClass:
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
  envVars:
  - name: database__client
    value: mysql
  - name: database__connection__host
    value: ghost-mysql
  - name: database__connection__user
    value: ghost
  - name: database__connection__password
    value: ghost
  - name: database__connection__database
    value: ghost
  - name: url
    value: http://ghost.lacolhost.com:81
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /var/lib/ghost/content
    name: ghost-volume
    size: 1Gi
    storageClass:
  web:
    replicaCount: 1
  worker:
    replicaCount: 0