apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: memos
spec:
  name: memos
  deploymentstrategy: docker
  image:
    repository: neosmemo/memos
    tag: latest
    containerPort: "5230"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /var/opt/memos
    name: memos-data
    size: 1Gi
    storageClass:
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
