name: Memos
description: 'Memos is a simple note taking app. '
tags:
- note taking
source: https://github.com/usememos/memos
website: https://usememos.com/
icon: https://avatars.githubusercontent.com/u/95764151?s=200&v=4
screenshots:
- https://usememos.com/demo.webp
