apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: go-httpbin
spec:
  name: go-httpbin
  deploymentstrategy: docker
  image:
    repository: mccutchen/go-httpbin
    tag: latest
    containerPort: "8080"
  addons: []
  envVars: []
  cronjobs: []
  extraVolumes: []
  web:
    replicaCount: 1
  worker:
    replicaCount: 0