apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: bitwarden
    labels:
        manager: kubero
spec:
    name: bitwarden
    deploymentstrategy: docker
    envVars:
        - name: BW_DB_PROVIDER
          value: postgresql
        - name: BW_DB_SERVER
          value: bitwarden-postgresql
        - name: BW_DB_DATABASE
          value: bitwarden
        - name: BW_DB_USERNAME
          value: bitwarden
        - name: BW_DB_PASSWORD
          value: bitwarden
        - name: BW_DOMAIN
          value: bitwarden.localhost
        - name: BW_INSTALLATION_ID
          value: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
        - name: BW_INSTALLATION_KEY
          value: XXXXXXXXXXXXXXXXXXXX
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /etc/bitwarden
          name: bitwarden
          size: 1Gi
          storageClass:
    cronjobs: []
    addons:
        - displayName: Postgresql
          env: []
          icon: /img/addons/postgresql.png
          id: kubero-operator
          kind: KuberoPostgresql
          resourceDefinitions:
              KuberoPostgresql:
                  apiVersion: application.kubero.dev/v1alpha1
                  kind: KuberoPostgresql
                  metadata:
                      name: bitwarden-postgresql
                  spec:
                      postgresql:
                          global:
                              postgresql:
                                  auth:
                                      database: bitwarden
                                      password: bitwarden
                                      postgresPassword: bitwarden
                                      username: bitwarden
                              storageClass:
                          primary:
                              persistence:
                                  size: 1Gi
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: 8080
        pullPolicy: Always
        repository: bitwarden/self-host
        tag: beta
