apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: slink
    labels:
        manager: kubero
spec:
    name: slink
    deploymentstrategy: docker
    envVars:
        - name: SWOOLE_WORKER_NUM
          value: "4"
        - name: API_ENABLED
          value: "true"
        - name: CORS_ALLOW_ORIGIN
          value: ^https?://(localhost||slink\.yourdomain\.com|127\.0\.0\.1)(:[0-9]+)?$
        - name: USER_APPROVAL_REQUIRED
          value: "true"
        - name: USER_APPROVAL_REQUIRED
          value: 15M
        - name: ORIGIN
          value: http://slink.yourdomain.com
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /var/data
          name: slink-volume
          size: 10Gi
          storageClass:
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "2000"
        pullPolicy: Always
        repository: anirdev/slink
        tag: latest
