apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: statping-ng
spec:
  name: statping-ng
  deploymentstrategy: docker
  image:
    repository: adamboutcher/statping-ng
    tag: latest
    containerPort: "8080"
  addons: []
  envVars:
  - name: STATPING_DIR
    value: /data
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /data
    name: statping-volume
    size: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0