name: Nats
description: 'Connective Technology for Adaptive Edge & Distributed Systems'
tags:
- network
- pubsub
- microservices
source: https://github.com/nats-io/nats-server
website: https://nats.io
icon: https://avatars.githubusercontent.com/u/10203055?s=200&v=4
screenshots: []