apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: wikijs
spec:
  name: wikijs
  deploymentstrategy: docker
  image:
    repository: ghcr.io/requarks/wiki
    tag: latest
    containerPort: "3000"
  addons: []
  envVars:
  - name: DB_TYPE
    value: sqlite
  - name: DB_FILEPATH
    value: /wiki/data/wikisj.db
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /wiki/data
    name: wikijs-data
    size: 1Gi
    storageClass:
  web:
    replicaCount: 1
  worker:
    replicaCount: 0