apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: photoview
spec:
  name: photoview
  deploymentstrategy: docker
  image:
    repository: viktorstrate/photoview
    tag: "2"
    containerPort: "8080"
  addons:
  - displayName: Kubero Mysql
    env: []
    icon: /img/addons/MySQL.png
    id: kubero-operator
    kind: KuberoMysql
    resourceDefinitions:
      KuberoMysql:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoMysql
        metadata:
          name: photoview-mysql
        spec:
          mysql:
            auth:
              createDatabase: true
              database: photoview
              password: photoview
              rootPassword: rootpw
              username: photoview
            global:
              storageClass: default
            primary:
              persistence:
                accessModes:
                - ReadWriteOnce
                size: 1Gi
  envVars:
  - name: PROC_TYPE
    value: web
  - name: PORT
    value: "8080"
  - name: PHOTOVIEW_DATABASE_DRIVER
    value: "mysql"
  - name: PHOTOVIEW_MYSQL_URL
    value: "photoview:photoview@tcp(photoview-mysql)/photoview"
  - name: PHOTOVIEW_LISTEN_IP
    value: "0.0.0.0"
  - name: PHOTOVIEW_LISTEN_PORT
    value: "8080"
  - name: PHOTOVIEW_MEDIA_CACHE
    value: "/tmp"
  cronjobs: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /photoview/images
    name: photoview-images
    size: 1Gi
    storageClass: default
  web:
    replicaCount: 1
  worker:
    replicaCount: 0